# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim
WORKDIR /app
ENV PYTHONUNBUFFERED=1
# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install python-dotenv mcp llama-index-llms-openai llama-index-indices-managed-llama-cloud llama-index-tools-mcp
# Copy application code
COPY . /app
# Default command
CMD ["python","mcp-server.py"]
